[package]
name = "stammer"
version = "0.1.0"
authors = ["Liu Xiaoyi <circuitcoder0@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
failure = "0.1.5"
